export const defaultFormData = {
  name: "",
  email: "",
  phone: "",
  linkedIn: "",
  github: "",
  portfolio: "",
  university: "",
  major: "",
  location: "",
  gradDate: "",
  professionalSummary: "",
  certifications: [],
  experiences: [],
  projects: [],
  skillsTitle: "Technical Skills",
  skillsContent: "",
};
